#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/compat-contract-manifest.sh"

HYPRLAND_SOURCE=${1:-${HYPRLAND_SOURCE:-/home/douglas/src/hyprland}}
VERSION_FILE="$HYPRLAND_SOURCE/VERSION"

if [[ ! -f "$VERSION_FILE" ]]; then
  printf 'Missing required Hyprland VERSION file: %s\n' "$VERSION_FILE" >&2
  exit 2
fi

TARGET_VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
mkdir -p "$CONTRACTS_DIR"

render_contract_file() {
  local out_path=$1
  local scope=$2
  local version=$3
  local temp_file
  temp_file="$(mktemp)"

  printf '# generated by scripts/generate-compat-contract.sh\n' > "$temp_file"
  printf '# target_version=%s\n' "$version" >> "$temp_file"
  printf '# scope=%s\n' "$scope" >> "$temp_file"

  if [[ "$scope" == "core" ]]; then
    compat_core_builtin_contracts_stream >> "$temp_file"
  else
    compat_surface_builtin_contracts_stream >> "$temp_file"
  fi

  mv "$temp_file" "$out_path"
}

render_contract_file "$CORE_GENERATED_CONTRACTS_FILE" "core" "$TARGET_VERSION"
render_contract_file "$SURFACE_GENERATED_CONTRACTS_FILE" "surface" "$TARGET_VERSION"

if [[ ! -f "$CORE_OVERRIDE_CONTRACTS_FILE" ]]; then
  printf '# Optional overrides: label<TAB>hyprland_path<TAB>owner<TAB>pattern\n' \
    > "$CORE_OVERRIDE_CONTRACTS_FILE"
fi

if [[ ! -f "$SURFACE_OVERRIDE_CONTRACTS_FILE" ]]; then
  printf '# Optional overrides: label<TAB>hyprland_path<TAB>owner<TAB>pattern\n' \
    > "$SURFACE_OVERRIDE_CONTRACTS_FILE"
fi

printf 'Generated contract baselines for Hyprland %s\n' "$TARGET_VERSION"
printf ' - %s\n' "$CORE_GENERATED_CONTRACTS_FILE"
printf ' - %s\n' "$SURFACE_GENERATED_CONTRACTS_FILE"
