#!/usr/bin/env bash
set -euo pipefail

printf 'Manual runtime checklist:\n'
printf '\n'
printf '1. Drag a tiled window across overview workspaces.\n'
printf '   Pass: the dragged window stays attached to the cursor, renders once, and drops on the expected workspace.\n'
printf '   Fail: duplicate dragged windows, large drag offset, hidden selected workspace, or stuck mouse bind mode.\n'
printf '\n'
printf '2. Run hyprtasking:movewindow in each direction from an occupied workspace.\n'
printf '   Pass: the hovered window moves to the target workspace, focus follows the move, and cursor/workspace state stays aligned.\n'
printf '   Fail: cursor ends up on the old workspace, the wrong window moves, or the target workspace transition is visually wrong.\n'
printf '\n'
printf '3. Open and interrupt gesture navigation mid-open and mid-move.\n'
printf '   Pass: the owning overview closes or recovers cleanly, and swipe state does not stay stuck.\n'
printf '   Fail: input feels captured, cursor override sticks, or a later gesture acts on the wrong monitor/view.\n'
printf '\n'
printf '4. Reload Hyprland while the overview is open.\n'
printf '   Pass: Hyprtasking reloads cleanly, dispatchers remain registered, and the compositor stays usable.\n'
printf '   Fail: invalid dispatcher, overview remains half-open, cursor override persists, or Hyprland becomes unstable.\n'
printf '\n'
printf '5. If available, remove or disable a monitor while the overview or a gesture is active.\n'
printf '   Pass: stale views disappear cleanly and no drag/gesture state survives the topology change.\n'
printf '   Fail: crash, frozen input, or callbacks acting on a removed monitor.\n'
